[build]
  command = "npm run build" # Adjust to match your build command
  publish = "dist"          # Set to your output directory (e.g., "dist" or "build")

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
